---
layout: home
---

# Xin chào! 👋  
Mình là Mỹ Duyên – một người yêu thích việc tìm tòi và công nghệ 🌸  
Đây là trang cá nhân của mình được host bằng GitHub Pages.

- 💻 Kỹ năng: HTML, CSS, JavaScript, C#
- 📘 Dự án: Web bán hàng, xây dựng học liệu số, tìm hiểu học tập chuyển giao để phân loại ung thư

> Cảm ơn bạn đã ghé thăm!
